const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];let auth=sessionStorage.getItem('msdAuth')||'',cache=[],stats={};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function headers(json=false){return {Authorization:auth,...(json?{'Content-Type':'application/json'}:{})}}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...headers(!!opt.json)};if(opt.json){opt.body=JSON.stringify(opt.json);delete opt.json;}const r=await fetch(url,opt),d=await r.json().catch(()=>({}));if(r.status===401){logout();throw Error('Login expired');}if(!r.ok)throw Error(d.error||'Request failed');return d;}
async function login(){auth='Basic '+btoa($('#user').value+':'+$('#pass').value);try{await api('/api/admin/stats');sessionStorage.setItem('msdAuth',auth);showDash();await loadAll()}catch(e){$('#loginMsg').innerHTML='<div class="error">Invalid admin login</div>';auth='';}}
function showDash(){if(!auth)return;$('#loginView').classList.add('hidden');$('#dash').classList.remove('hidden')}
function logout(){sessionStorage.removeItem('msdAuth');location.reload()}
function setTab(name){$$('.erp-section').forEach(x=>x.classList.add('hidden'));$('#tab-'+name).classList.remove('hidden');$$('.erp-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));if(name==='customers')loadCustomers();if(name==='accounts')loadExpenses();if(name==='settings')loadSettings();}
async function loadAll(){await Promise.all([loadStats(),loadWorks(),loadServices()]);}
async function loadStats(){stats=await api('/api/admin/stats');const cards=[['Total Works',stats.total,'🧾'],['Customers',stats.customers,'👥'],['Total Fee',money(stats.totalFee),'💼'],['Paid',money(stats.paid),'✅'],['Due',money(stats.due),'⏳'],['Expenses',money(stats.expenses),'💸'],['Profit',money(stats.profit),'📈'],['Completed',stats.completed,'🏁']];$('#stats').innerHTML=cards.map(x=>`<div class="stat"><span>${x[2]} ${x[0]}</span><b>${x[1]}</b></div>`).join('');$('#snapshot').innerHTML=`<div><span>Today Collection</span><b>${money(stats.todayPaid)}</b></div><div><span>Processing</span><b>${stats.processing}</b></div><div><span>Pending Due</span><b>${money(stats.due)}</b></div><div><span>Net Profit</span><b>${money(stats.profit)}</b></div>`;$('#accountSummary').innerHTML=`<div><span>Total Fee</span><b>${money(stats.totalFee)}</b></div><div><span>Total Paid</span><b>${money(stats.paid)}</b></div><div><span>Total Due</span><b>${money(stats.due)}</b></div><div><span>Total Expense</span><b>${money(stats.expenses)}</b></div><div><span>Net Profit</span><b>${money(stats.profit)}</b></div>`;}
async function loadWorks(){const q=new URLSearchParams({q:$('#search')?.value||'',status:$('#filter')?.value||'All'});cache=await api('/api/admin/requests?'+q);$('#requests').innerHTML=cache.length?cache.map(card).join(''):'<div class="panel" style="text-align:center;color:#aebdd1">No works found.</div>';}
function card(x){const files=[...(x.files||[]),...(x.paymentProof?[{...x.paymentProof,name:'Payment: '+x.paymentProof.name}]:[])];return `<article class="request"><div class="request-top"><div><h3>${esc(x.id)} — ${esc(x.name)}</h3><div class="small">${new Date(x.createdAt).toLocaleString()} • ${esc(x.mobile)} • ${esc(x.service)}</div></div><span class="status-badge">${esc(x.status)}</span></div><div class="meta erp-meta"><div>💼 Fee<br><b>${money(x.totalFee)}</b></div><div>✅ Paid<br><b>${money(x.paidAmount)}</b></div><div>⏳ Due<br><b>${money(x.dueAmount)}</b></div><div>💳 Payment<br><b>${esc(x.paymentStatus)}</b></div></div><p>${esc(x.message||'No extra message')}</p><div class="files">${files.map(f=>`<a class="file-link" href="${esc(f.url)}" target="_blank">📎 ${esc(f.name)}</a>`).join('')||'<span class="small">No files</span>'}</div><div class="admin-actions erp-work-actions"><select id="status-${x.id}">${['Received','Processing','Waiting for Customer','Completed','Cancelled'].map(v=>`<option ${v===x.status?'selected':''}>${v}</option>`).join('')}</select><input id="fee-${x.id}" type="number" min="0" value="${Number(x.totalFee||0)}" placeholder="Total Fee"><input id="paid-${x.id}" type="number" min="0" value="${Number(x.paidAmount||0)}" placeholder="Paid"><input id="note-${x.id}" value="${esc(x.adminNote||'')}" placeholder="Admin note"><button class="btn btn-primary" onclick="saveWork('${x.id}')">Save</button><a class="btn btn-outline" target="_blank" href="https://wa.me/91${esc(x.mobile)}?text=${encodeURIComponent('Namaste '+x.name+', aapke work '+x.id+' ka status: '+x.status+'. Due: ₹'+x.dueAmount+'. - MS MANISH DIGITAL')}">WhatsApp</a><a class="btn btn-outline" target="_blank" href="/receipt?id=${encodeURIComponent(x.id)}&mobile=${encodeURIComponent(x.mobile)}">Receipt</a><button class="btn danger" onclick="removeWork('${x.id}')">Delete</button></div></article>`}
async function saveWork(id){try{await api('/api/admin/requests/'+id,{method:'PATCH',json:{status:$('#status-'+id).value,totalFee:$('#fee-'+id).value,paidAmount:$('#paid-'+id).value,adminNote:$('#note-'+id).value}});await Promise.all([loadWorks(),loadStats()]);}catch(e){alert(e.message)}}
async function removeWork(id){if(!confirm('Delete this work and uploaded files?'))return;await api('/api/admin/requests/'+id,{method:'DELETE'});await Promise.all([loadWorks(),loadStats()]);}
async function loadCustomers(){const rows=await api('/api/admin/customers'),q=($('#customerSearch').value||'').toLowerCase(),f=rows.filter(x=>[x.name,x.mobile].some(v=>String(v).toLowerCase().includes(q)));$('#customers').innerHTML=`<table class="erp-table"><thead><tr><th>Customer</th><th>Mobile</th><th>Works</th><th>Total Fee</th><th>Paid</th><th>Due</th><th>Last Work</th></tr></thead><tbody>${f.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.mobile)}</td><td>${x.works}</td><td>${money(x.totalFee)}</td><td>${money(x.paid)}</td><td class="due-text">${money(x.due)}</td><td>${new Date(x.lastWorkAt).toLocaleDateString()}</td></tr>`).join('')}</tbody></table>`;}
async function loadExpenses(){const rows=await api('/api/admin/expenses');$('#expenses').innerHTML=`<table class="erp-table"><thead><tr><th>Date</th><th>Expense</th><th>Note</th><th>Amount</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.date)}</td><td><b>${esc(x.title)}</b></td><td>${esc(x.note||'-')}</td><td>${money(x.amount)}</td><td><button class="btn danger" onclick="deleteExpense('${x.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="5">No expenses</td></tr>'}</tbody></table>`;await loadStats();}
async function deleteExpense(id){if(!confirm('Delete expense?'))return;await api('/api/admin/expenses/'+id,{method:'DELETE'});loadExpenses();}
async function loadServices(){const rows=await api('/api/admin/services');$('#serviceText').value=rows.join('\n');$('#quickService').innerHTML='<option value="">-- Select Service --</option>'+rows.map(x=>`<option>${esc(x)}</option>`).join('');}
async function loadSettings(){const d=await api('/api/admin/settings');Object.entries(d).forEach(([k,v])=>{const el=$(`#settingsForm [name="${k}"]`);if(el)el.value=v||''});}
function download(path,name){fetch(path,{headers:headers()}).then(r=>{if(!r.ok)throw Error();return r.blob()}).then(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}).catch(()=>alert('Download failed'))}
async function restore(){const f=$('#restoreFile').files[0];if(!f)return alert('Select JSON backup');if(!confirm('Current ERP data will be replaced. Continue?'))return;const fd=new FormData();fd.append('backup',f);const r=await fetch('/api/admin/restore',{method:'POST',headers:headers(),body:fd}),d=await r.json();alert(r.ok?'Backup restored: '+d.count:d.error);if(r.ok)loadAll();}
$('#loginBtn').onclick=login;$('#pass').onkeydown=e=>{if(e.key==='Enter')login()};$('#logoutBtn').onclick=logout;$$('.erp-tabs button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#search').oninput=()=>{clearTimeout(window.t);window.t=setTimeout(loadWorks,250)};$('#filter').onchange=loadWorks;$('#customerSearch').oninput=()=>{clearTimeout(window.ct);window.ct=setTimeout(loadCustomers,250)};$('#exportBtn').onclick=()=>download('/api/admin/export','ms-manish-erp-report.csv');$('#backupBtn').onclick=$('#backupBtn2').onclick=()=>download('/api/admin/backup','ms-manish-erp-backup.json');$('#restoreBtn').onclick=restore;
$('#quickWork').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/requests',{method:'POST',json:Object.fromEntries(new FormData(e.target))});e.target.reset();alert('Work added successfully');await loadAll();setTab('works')}catch(err){alert(err.message)}};
$('#expenseForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/expenses',{method:'POST',json:Object.fromEntries(new FormData(e.target))});e.target.reset();loadExpenses()}catch(err){alert(err.message)}};
$('#saveServices').onclick=async()=>{try{await api('/api/admin/services',{method:'PUT',json:{services:$('#serviceText').value.split('\n').map(x=>x.trim()).filter(Boolean)}});alert('Services saved');loadServices()}catch(e){alert(e.message)}};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/settings',{method:'PUT',json:Object.fromEntries(new FormData(e.target))});alert('Settings saved')}catch(err){alert(err.message)}};
if(auth){showDash();loadAll();}
