const $=s=>document.querySelector(s);let cfg={};
const fallbackServices=['Online Form','Admit Card','Result','Scholarship / DBT Check','LNMU Admission','LNMU Registration','LNMU Exam Form','LNMU Internship Work','Student Credit Card','PAN Card','Passport - New / Renewal','Voter Card','APAAR / ABC ID','Income Certificate','Caste Certificate','Residence Certificate','EWS Certificate','NCL / OBC Certificate','Udyam Registration','Ayushman Card','EPFO / UAN','e-Shram Card','Ration Card','Bike Insurance','Resume / Biodata','Printout - B/W / Color','Xerox','Lamination','Spiral Binding','Other Online Work'];
const safe=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function fillServices(rows){const ss=$('#serviceSelect');const list=Array.isArray(rows)&&rows.length?rows:fallbackServices;if(ss)ss.innerHTML='<option value="">-- Select Service --</option>'+list.map(x=>`<option value="${safe(x)}">${safe(x)}</option>`).join('');}
async function init(){
  fillServices(fallbackServices);
  try{const r=await fetch('/api/services',{cache:'no-store'});if(r.ok){const rows=await r.json();fillServices(rows);}}catch(e){}
  try{const r=await fetch('/api/config',{cache:'no-store'});if(r.ok)cfg=await r.json();}catch(e){}
  cfg={shopName:'MS MANISH DIGITAL CYBER EXPERT',tagline:'Your Trusted Digital Service Partner',phone:'9229288090',email:'msmanishdcexpert@gmail.com',address:'Panchwati Chowk, Hospital Road, Rajnagar, Madhubani - 847235',...cfg};
  $('#shopName').textContent=cfg.shopName;$('#tagline').textContent=cfg.tagline;$('#phoneText').textContent='📱 '+cfg.phone;$('#emailText').textContent='✉️ '+cfg.email;$('#addressText').textContent='📍 '+cfg.address;$('#callBtn').href='tel:'+cfg.phone;const wa=`https://wa.me/91${cfg.phone}?text=${encodeURIComponent('Namaste, mujhe online work ke baare me help chahiye.')}`;$('#waBtn').href=wa;$('#chatWa').onclick=()=>window.open(wa,'_blank');
}
$('#workForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('#submitBtn'),out=$('#result');btn.disabled=true;btn.textContent='Uploading...';out.innerHTML='';try{const r=await fetch('/api/requests',{method:'POST',body:new FormData(e.target)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Submission failed');out.innerHTML=`<div class="success"><b>काम सफलतापूर्वक भेज दिया गया!</b><br>आपका Work ID: <strong>${d.id}</strong><br>इसे सुरक्षित रखें।<div style="margin-top:12px;display:flex;gap:8px;flex-wrap:wrap"><a class="btn btn-outline" href="/receipt?id=${encodeURIComponent(d.id)}&mobile=${encodeURIComponent(e.target.mobile.value)}" target="_blank">🧾 Receipt देखें</a><a class="btn btn-primary" target="_blank" href="https://wa.me/91${cfg.phone}?text=${encodeURIComponent('Namaste! Aapka kaam safaltapoorvak receive ho gaya hai. Aapka Work ID: Work ID: '+d.id)}">WhatsApp पर भेजें</a></div></div>`;e.target.reset();out.scrollIntoView({behavior:'smooth',block:'center'})}catch(err){out.innerHTML=`<div class="error">${err.message}</div>`}finally{btn.disabled=false;btn.textContent='🚀 काम भेजें'}});
$('#trackForm').addEventListener('submit',async e=>{e.preventDefault();const out=$('#statusResult'),fd=new FormData(e.target);out.innerHTML='<div class="notice">Checking...</div>';try{const q=new URLSearchParams({id:fd.get('id'),mobile:fd.get('mobile')}),r=await fetch('/api/status?'+q),d=await r.json();if(!r.ok)throw new Error(d.error);out.innerHTML=`<div class="status-card" style="padding:20px"><div class="status-head"><div><b>${d.id}</b><div class="small">${d.service} • ${d.name}</div></div><span class="status-badge">${d.status}</span></div><p>${d.adminNote?'<b>Admin Note:</b> '+d.adminNote:'आपका काम हमारी टीम के पास है।'}</p><div class="small">Payment: ${d.paymentStatus} • Fee: ₹${Number(d.totalFee||0)} • Paid: ₹${Number(d.paidAmount||0)} • Due: ₹${Number(d.dueAmount||0)}</div><div class="timeline">${(d.history||[]).map(h=>`<div class="timeline-item"><div><b>${h.status}</b><div class="small">${new Date(h.at).toLocaleString()}</div></div></div>`).join('')}</div><a class="btn btn-outline" style="margin-top:14px" href="/receipt?id=${encodeURIComponent(d.id)}&mobile=${encodeURIComponent(fd.get('mobile'))}" target="_blank">🧾 Receipt</a></div>`}catch(err){out.innerHTML=`<div class="error">${err.message}</div>`}});
$('#chatToggle').onclick=()=>$('#chatBox').classList.toggle('open');document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>$('#chatAnswer').innerHTML=`<div class="bubble" style="margin-top:10px">${b.dataset.answer}</div>`);init();
